spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL;
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: com.alntvs.*
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
